"""initial schema freeze

Revision ID: f02bb8c1792d
Revises: 
Create Date: 2026-06-13 20:24:36.794905
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f02bb8c1792d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_token_subject_id'), 'refresh_token', ['subject_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('hunter', 'admin', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('va',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('whatsapp_jid', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('whatsapp_jid')
    )
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('greenhouse', 'lever', 'ashby', 'adzuna', 'serpapi', name='jobsourcename', native_enum=False), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=True),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('track', sa.Enum('frontend', 'backend', 'general', name='track', native_enum=False), nullable=True),
    sa.Column('track_override', sa.Enum('frontend', 'backend', 'general', name='track', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('discovered', 'scored', 'rejected', 'tailoring', 'ready', 'submitted', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_job_user_dedupe')
    )
    op.create_index(op.f('ix_job_user_id'), 'job', ['user_id'], unique=False)
    op.create_index('ix_job_user_status', 'job', ['user_id', 'status'], unique=False)
    op.create_index('ix_job_user_track', 'job', ['user_id', 'track'], unique=False)
    op.create_table('master_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('track', sa.Enum('frontend', 'backend', 'general', name='track', native_enum=False), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('experience', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('education', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('projects', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('truth_corpus', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track', name='uq_profile_user_track')
    )
    op.create_index(op.f('ix_master_profile_user_id'), 'master_profile', ['user_id'], unique=False)
    op.create_table('sending_domain',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('track', sa.Enum('frontend', 'backend', 'general', name='track', native_enum=False), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('resend_domain_id', sa.String(length=128), nullable=True),
    sa.Column('dkim_status', sa.Enum('pending', 'verified', 'failed', name='dnsstatus', native_enum=False), nullable=False),
    sa.Column('spf_status', sa.Enum('pending', 'verified', 'failed', name='dnsstatus', native_enum=False), nullable=False),
    sa.Column('dmarc_status', sa.Enum('pending', 'verified', 'failed', name='dnsstatus', native_enum=False), nullable=False),
    sa.Column('dns_records', sa.Text(), nullable=True),
    sa.Column('warmup_stage', sa.Enum('stage_1', 'stage_2', 'stage_3', 'full', name='warmupstage', native_enum=False), nullable=False),
    sa.Column('warmup_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_sent_count', sa.Integer(), nullable=False),
    sa.Column('daily_count_date', sa.Date(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('pause_reason', sa.String(length=255), nullable=True),
    sa.Column('bounce_rate', sa.Float(), nullable=False),
    sa.Column('complaint_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', name='uq_domain_name'),
    sa.UniqueConstraint('user_id', 'track', name='uq_domain_user_track')
    )
    op.create_index(op.f('ix_sending_domain_is_paused'), 'sending_domain', ['is_paused'], unique=False)
    op.create_index(op.f('ix_sending_domain_user_id'), 'sending_domain', ['user_id'], unique=False)
    op.create_table('va_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('va_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('track', sa.Enum('frontend', 'backend', 'general', name='track', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['va_id'], ['va.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('va_id', 'user_id', 'track', name='uq_assignment')
    )
    op.create_index('ix_assignment_user_track', 'va_assignment', ['user_id', 'track'], unique=False)
    op.create_index(op.f('ix_va_assignment_user_id'), 'va_assignment', ['user_id'], unique=False)
    op.create_index(op.f('ix_va_assignment_va_id'), 'va_assignment', ['va_id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('role_type', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('linkedin', sa.Text(), nullable=True),
    sa.Column('apollo_id', sa.String(length=128), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'email', name='uq_contact_job_email')
    )
    op.create_index(op.f('ix_contact_job_id'), 'contact', ['job_id'], unique=False)
    op.create_index('ix_contact_user_email', 'contact', ['user_id', 'email'], unique=False)
    op.create_index(op.f('ix_contact_user_id'), 'contact', ['user_id'], unique=False)
    op.create_table('generated_cv',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('master_profile_id', sa.Uuid(), nullable=True),
    sa.Column('cv_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('latex_source', sa.Text(), nullable=True),
    sa.Column('tex_key', sa.String(length=512), nullable=True),
    sa.Column('pdf_key', sa.String(length=512), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('tailoring_diff', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('rendering', 'ready', 'failed', name='cvstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['master_profile_id'], ['master_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_cv_job')
    )
    op.create_index(op.f('ix_generated_cv_job_id'), 'generated_cv', ['job_id'], unique=False)
    op.create_index(op.f('ix_generated_cv_user_id'), 'generated_cv', ['user_id'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('generated_cv_id', sa.Uuid(), nullable=True),
    sa.Column('va_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'interview', 'rejected', 'offer', 'failed', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('submission_channel', sa.String(length=64), nullable=True),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_cv_id'], ['generated_cv.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['va_id'], ['va.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_application_job')
    )
    op.create_index(op.f('ix_application_job_id'), 'application', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_user_id'), 'application', ['user_id'], unique=False)
    op.create_index('ix_application_user_status', 'application', ['user_id', 'status'], unique=False)
    op.create_table('thread',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('sending_domain_id', sa.Uuid(), nullable=False),
    sa.Column('reply_address', sa.String(length=320), nullable=False),
    sa.Column('root_message_id', sa.String(length=512), nullable=True),
    sa.Column('state', sa.Enum('open', 'awaiting_va', 'awaiting_send', 'closed', name='threadstate', native_enum=False), nullable=False),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sending_domain_id'], ['sending_domain.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reply_address', name='uq_thread_reply_address')
    )
    op.create_index(op.f('ix_thread_application_id'), 'thread', ['application_id'], unique=False)
    op.create_index('ix_thread_root_message', 'thread', ['root_message_id'], unique=False)
    op.create_index(op.f('ix_thread_user_id'), 'thread', ['user_id'], unique=False)
    op.create_table('outreach',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('sending_domain_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=True),
    sa.Column('sequence_step', sa.Enum('first', 'followup1', 'followup2', 'stopped', name='sequencestep', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('drafted', 'review', 'queued', 'sent', 'bounced', 'replied', 'stopped', name='outreachstatus', native_enum=False), nullable=False),
    sa.Column('reply_address', sa.String(length=320), nullable=True),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sending_domain_id'], ['sending_domain.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'contact_id', 'sequence_step', name='uq_outreach_step')
    )
    op.create_index(op.f('ix_outreach_application_id'), 'outreach', ['application_id'], unique=False)
    op.create_index('ix_outreach_status_next', 'outreach', ['status', 'next_action_at'], unique=False)
    op.create_index(op.f('ix_outreach_user_id'), 'outreach', ['user_id'], unique=False)
    op.create_index('ix_outreach_user_sent', 'outreach', ['user_id', 'sent_at'], unique=False)
    op.create_table('reply',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='replydirection', native_enum=False), nullable=False),
    sa.Column('from_addr', sa.String(length=320), nullable=True),
    sa.Column('to_addr', sa.String(length=320), nullable=True),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('in_reply_to', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('classification', sa.Enum('routine', 'substantive', name='replyclassification', native_enum=False), nullable=True),
    sa.Column('suggested_draft', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reply_in_reply_to', 'reply', ['in_reply_to'], unique=False)
    op.create_index('ix_reply_message_id', 'reply', ['message_id'], unique=False)
    op.create_index(op.f('ix_reply_thread_id'), 'reply', ['thread_id'], unique=False)
    op.create_index('ix_reply_thread_received', 'reply', ['thread_id', 'received_at'], unique=False)
    op.create_index(op.f('ix_reply_user_id'), 'reply', ['user_id'], unique=False)
    op.create_table('dossier',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('reply_id', sa.Uuid(), nullable=False),
    sa.Column('va_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('pushed', 'va_replied', 'relayed', 'closed', name='dossierstatus', native_enum=False), nullable=False),
    sa.Column('bridge_message_ref', sa.String(length=255), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['reply.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['va_id'], ['va.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dossier_thread', 'dossier', ['thread_id'], unique=False)
    op.create_index(op.f('ix_dossier_user_id'), 'dossier', ['user_id'], unique=False)
    op.create_index('ix_dossier_va_status', 'dossier', ['va_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dossier_va_status', table_name='dossier')
    op.drop_index(op.f('ix_dossier_user_id'), table_name='dossier')
    op.drop_index('ix_dossier_thread', table_name='dossier')
    op.drop_table('dossier')
    op.drop_index(op.f('ix_reply_user_id'), table_name='reply')
    op.drop_index('ix_reply_thread_received', table_name='reply')
    op.drop_index(op.f('ix_reply_thread_id'), table_name='reply')
    op.drop_index('ix_reply_message_id', table_name='reply')
    op.drop_index('ix_reply_in_reply_to', table_name='reply')
    op.drop_table('reply')
    op.drop_index('ix_outreach_user_sent', table_name='outreach')
    op.drop_index(op.f('ix_outreach_user_id'), table_name='outreach')
    op.drop_index('ix_outreach_status_next', table_name='outreach')
    op.drop_index(op.f('ix_outreach_application_id'), table_name='outreach')
    op.drop_table('outreach')
    op.drop_index(op.f('ix_thread_user_id'), table_name='thread')
    op.drop_index('ix_thread_root_message', table_name='thread')
    op.drop_index(op.f('ix_thread_application_id'), table_name='thread')
    op.drop_table('thread')
    op.drop_index('ix_application_user_status', table_name='application')
    op.drop_index(op.f('ix_application_user_id'), table_name='application')
    op.drop_index(op.f('ix_application_job_id'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_generated_cv_user_id'), table_name='generated_cv')
    op.drop_index(op.f('ix_generated_cv_job_id'), table_name='generated_cv')
    op.drop_table('generated_cv')
    op.drop_index(op.f('ix_contact_user_id'), table_name='contact')
    op.drop_index('ix_contact_user_email', table_name='contact')
    op.drop_index(op.f('ix_contact_job_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_va_assignment_va_id'), table_name='va_assignment')
    op.drop_index(op.f('ix_va_assignment_user_id'), table_name='va_assignment')
    op.drop_index('ix_assignment_user_track', table_name='va_assignment')
    op.drop_table('va_assignment')
    op.drop_index(op.f('ix_sending_domain_user_id'), table_name='sending_domain')
    op.drop_index(op.f('ix_sending_domain_is_paused'), table_name='sending_domain')
    op.drop_table('sending_domain')
    op.drop_index(op.f('ix_master_profile_user_id'), table_name='master_profile')
    op.drop_table('master_profile')
    op.drop_index('ix_job_user_track', table_name='job')
    op.drop_index('ix_job_user_status', table_name='job')
    op.drop_index(op.f('ix_job_user_id'), table_name='job')
    op.drop_table('job')
    op.drop_table('va')
    op.drop_table('user')
    op.drop_index(op.f('ix_refresh_token_subject_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
